######服务器参数############
server:
  port: 8080
  servlet:
    context-path: /
        
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    name: mfyx
    url: 'jdbc:mysql://47.106.70.72:3306/db_mfyx'
    username: 'aoksen'
    password: 'YesOrNoAnd0+1'
        # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver    
  servlet: 
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
        
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.mofanyouxuan.model
 
logging:
  level:
    com.mofangyouxuan: DEBUG

  
######业务参数############
#访问微信管理平台服务接口
wxmp:
  wxmp-server-url: 'http://localhost:9000'
  qrcode-apply-url: '/qrcode/createTmp'
  qrcode-get-url: '/qrcode/getqrcode'
  qrcode-show-url: '/qrcode/show/'

#微信支付参数
wxpay:
  mchtid: '1503812541'
  appid: 'wx34a58dad7a6542ca'
  notify-server-url: 'https://pay.mofangyouxuan.com'
  pay-notify-url: '/wxpay/notify/pay'
  refund-notify-url: '/wxpay/notify/refund'
  wx-fee-rate: 0.007
  cert-key-dir: '/Users/jeekhan/wxpay/'

#信息管理平台
messmp:
  messmp-server-url: 'http://localhost:8888'
  verify-phone-vericode: '/sms/vericode/verify'
  verify-email-vericode: '/email/vericode/verify'
  send-phone-resetpwd: '/sms/resetpwd/send'
  send-email-resetpwd: '/email/resetpwd/send'
  
######系统参数############  
sys:
  tmp-file-dir: '/Users/jeekhan/mfyx/tmp/'  #系统临时目录
  user-img-path: '/Users/jeekhan/mfyx/user-img/' #用户图片主目录
  partner-cert-dir: '/Users/jeekhan/mfyx/partner-cert/'   #合作伙伴证件照片主目录
  image-gallery-dir: '/Users/jeekhan/mfyx/image-gallery/' #系统图库主目录
  image-folder-level-limit: 3   #文件夹最多三层
  image-file-all-limit: 100     #每个会员最多可有100个文件（普通文件和目录）
  image-folder-file-limit: 100   #每个文件夹下最多可有100个文件（普通文件和目录）
  
  activate-vip-need-score: 1000 #激活会员需要多少积分
  spread-per-user-score: 100 #每推广一个用户可获得多少积分
  
  postage-cnt-limit: 20 #每个合作伙伴可添加的运费模版数量限制
  goods-cnt-limit: 30 #每个合作伙伴可添加的商品数量限制

  receiver-cnt-limit: 5 #每个用户可添加的收货人信息数量限制
  
  order-4pay-cnt-all-limit: 30   #每个用户可持有的所有待付款订单数
  order-4pay-cnt-goods-limit: 1   #每个用户可持有的单个商品待付款订单数
  order-nodelivery-days-4refund: 3   #超过3天卖家未发货买家可申请退款
  order-nosign-days-4refund: 10   #至卖家发货之后超过10天买家没有获得签收可申请退款
  
  