######服务器参数############
server:
  port: 8080
  servlet:
    context-path: /
        
  tomcat:
    uri-encoding: UTF-8
spring:
    datasource:
        name: mfyx
        url: 'jdbc:mysql://172.18.235.107:3306/db_mfyx'
        username: 'aoksen'
        password: 'YesOrNoAnd0+1'
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.mofanyouxuan.model
 
logging:
  level:
    com.jeekhan.wx.mapper: DEBUG

  
######业务参数############
#访问微信管理平台服务接口
wxmp:
  wxmp-server-url: 'http://172.18.235.107:9000'
  qrcode-apply-url: '/qrcode/createTmp'
  qrcode-get-url: '/qrcode/getqrcode'
  qrcode-show-url: '/qrcode/show/'
  
  
######系统参数############  
sys:
  tmp-file-dir: '/tmp/mfyx-server/'
  partner-cert-dir: '/var/mfyx-server/partner-cert/'
  partner-goods-dir: '/var/mfyx-server/goods-img/'
  


  