######服务器参数############
server:
  port: 8080
  servlet:
    context-path: /mfyx
        
  tomcat:
    uri-encoding: UTF-8
spring:
    datasource:
        name: mfyx
        url: 'jdbc:mysql://47.106.70.72:3306/db_mfyx'
        username: 'aoksen'
        password: 'YesOrNoAnd0+1'
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.mofanyouxuan.model
 
logging:
  level:
    com.jeekhan.wx.mapper: DEBUG

  
######业务参数############
#用户注册URL、注销URL
busi:
  wxmp-server-url: 'http://localhost:9000/wxmp'
  qrcode-apply-url: '/qrcode/createTmp'
  qrcode-get-url: '/qrcode/getqrcode'
  qrcode-show-url: '/qrcode/show/'
  
  
######系统参数############  
sys:
  tmp-file-dir: '/Users/jeekhan/mfyx/tmp/'


  