######服务器参数############
server:
  port: 8080
  servlet:
    context-path: /
        
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    name: mfyx
    url: 'jdbc:mysql://192.168.0.108:3306/db_mfyx'
    username: 'leyi'
    password: 'leyipwd'
        # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver   
         
  servlet: 
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
      
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.mofanyouxuan.model
 
logging:
  level:
    com.mofangyouxuan: DEBUG

  
######业务参数############
#访问微信管理平台服务接口
wxmp:
  wxmp-server-url: 'http://192.168.0.102:9000'
  wxmp-server-url-4user: 'http://192.168.0.102:9000'
  qrcode-apply-url: '/qrcode/createTmp'
  qrcode-get-url: '/qrcode/getqrcode'
  qrcode-show-url: '/qrcode/show/'

#微信支付参数
wxpay:
  mchtid: '1503812541'
  appid: 'wx34a58dad7a6542ca'
  notify-server-url: 'https://pay.mofangyouxuan.com'
  pay-notify-url: '/wxpay/notify/pay'
  refund-notify-url: '/wxpay/notify/refund'
  fee-rate-use-wxpay: 0.037   #微信支付手续费
  cert-key-dir: '/Users/jeekhan/mfpay/wxpay/'

#支付宝支付参数
alipay:
  appid: '2018061260389188'
  notify-server-url: 'https://pay.mofangyouxuan.com'
  return-server-url: 'https://h5.mofangyouxuan.com'
  pay-notify-url: '/alipay/notify'
  pay-return-url: '/pay/finish/{orderId}'
  fee-rate-use-alipay: 0.007   #支付宝支付手续费
  cert-key-dir: '/Users/jeekhan/mfpay/alipay/'
  seller-email: 'zhaofachun@mofangyouxuan.com'
  
#信息管理平台
messmp:
  messmp-server-url: 'http://192.168.0.102:8888'
  verify-phone-vericode: '/sms/vericode/verify'
  verify-email-vericode: '/email/vericode/verify'
  send-phone-resetpwd: '/sms/resetpwd/send'
  send-email-resetpwd: '/email/resetpwd/send'
  
#物流查询
logistics:
  alicloudapi-appcode: 'c1f1103e8f2a4283a6ca696cddb4242c' 

######系统参数############  
sys:
  pay-bills-dir: '/Users/jeekhan/mfyx/paybills/'  #支付对账单
  tmp-file-dir: '/Users/jeekhan/mfyx/tmp/'  #系统临时目录
  user-img-path: '/Users/jeekhan/mfyx/user-img/' #用户图片主目录
  partner-img-dir: '/Users/jeekhan/mfyx/partner-img/'   #合作伙伴照片主目录
  image-gallery-dir: '/Users/jeekhan/mfyx/image-gallery/' #系统图库主目录
  image-folder-level-limit: 3     #文件夹最多三层，后续针对用户进行付费控制
  image-file-all-limit: 100       #每个会员最多可有100个文件（普通文件和目录），后续针对用户进行付费控制
  image-folder-file-limit: 100    #每个文件夹下最多可有100个文件（普通文件和目录），后续针对用户进行付费控制
  
  vip_activate_need_score: 500 #激活会员需要多少积分
  spread_per_user_score: 20     #每推广一个用户可获得多少积分
  spread_user_profit_ratio: 0.1 #推广买家可获得所推广买家交易额的分润利率，百分数
  partner_open_need_socre: 1000   #开通合作伙伴需要多少积分
  trade_score_one_yuan: 1        #每消费一元获得多少积分
  
  postage-cnt-limit: 20 #每个合作伙伴可添加的运费模版数量限制，后续针对用户进行付费控制
  goods-cnt-limit: 30   #每个合作伙伴可添加的商品数量限制，后续针对用户进行付费控制

  receiver-cnt-limit: 5 #每个用户可添加的收货人信息数量限制
  
  order-4pay-cnt-all-limit: 30    #每个用户可持有的所有待付款订单数
  order-4pay-cnt-goods-limit: 1   #每个用户可持有的单个商品待付款订单数
  order-nodelivery-days-4refund: 3    #超过3天卖家未发货买家可申请退款
  order-nosign-days-4refund: 7        #自卖家发货之后超过N天买家没有获得签收可申请退款
  order-sign-prolong-days: 5      #每次申请可延长签收天数
  order-auto-appr-days: 7         #自从签收后超过N天没有评价则系统自动好评
  order-amount-unfreeze-days: 10  #自从买家评价后超过N天后商家卖款解冻
  
  user-collection-limit: 20 #每个用户可有的收藏数量
  
  vip-account-cnt-limit: 5 #会员用户的账户数量限制
  
  login-errcnt-limit: 5 #每日错误密码登录次数
  
  
  
  